### ISSUE TITLE
Statically linked openssl

### ISSUE THREAD

**Issue by blastehh** [z4yx/pam_rssh#11]
I compiled this on a system with openssl 1.1.1, but couldn't do the same for a system running openssl 3.0.
It compiles fine but ends up throwing this error in the logs:
```
PAM unable to dlopen(/usr/local/lib/libpam_rssh.so): libssl.so.1.1: cannot open shared object file: No such file or directory
```

I ended getting it to work on an openssl 3.0 system by recompiling using this method to make openssl statically linked https://docs.rs/openssl/0.10.34/openssl/#vendored

Not really sure if it's hardcoded for openssl 1.1.1 or if I messed something up to make it not work with 3.0 tbh.

**Comment by z4yx** [comment]
I havn't tried building with openssl 3.0. But according to the document of openssl binding library, `OpenSSL versions 1.0.1 through 3.x.x and LibreSSL versions 2.5 through 3.7.x are supported`. 
I didn't hard-code any version number. Maybe your system has two versions of openssl installed, while the Rust compiler links to 1.1.1 instead of 3.0.
